development:
  api_secret: <%= ENV['DISQUS_API_SECRET'] %>
  api_key: <%= ENV['DISQUS_API_KEY'] %>
  access_token: <%= ENV['DISQUS_ACCESS_TOKEN'] %>

production:
  api_secret: <%= ENV['DISQUS_API_SECRET'] %>
  api_key: <%= ENV['DISQUS_API_KEY'] %>
  access_token: <%= ENV['DISQUS_ACCESS_TOKEN'] %>
